#!/usr/bin/env bash
#MISE description="Lint the package"
#USAGE flag "-f --fix" help="Automatically fix linting issues where possible"
set -eo pipefail

if [ "$usage_fix" = "true" ]; then
    swiftformat .
    swiftlint lint --fix --quiet --config .swiftlint.yml Sources Tests Fixtures
else
    swiftformat . --lint
    swiftlint lint --quiet --config .swiftlint.yml Sources Tests Fixtures
fi
